#!/usr/bin/env sh

case "$INSIDE_EMACS" in
    *magit) $GIT_EDITOR --eval "(magit-run-post-commit-functions 'post-commit)" ;;
esac

#echo "ORIG_HOOKS_PATH: $ORIG_HOOKS_PATH"

[ -x "$ORIG_HOOKS_PATH" ] && "$ORIG_HOOKS_PATH/$(basename $0)" "$@"
