#!/bin/sh

# Copyright (C) 2011 Peter J Weisberg.
#
# Magit is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# Magit is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Magit.  If not, see <http://www.gnu.org/licenses/>.

if [ -n "$1" ]; then
    dir=$(readlink -m "$1")
else
    dir=$(pwd)
fi

runmagit="(progn (magit-status \"$dir\")
                 (delete-other-windows))"

# Don't allow non-empty alternate editor
env | grep ^ALTERNATE_EDITOR=$ > /dev/null
if [ $? != 0 ]; then
    ALTERNATE_EDITOR=false
fi

if [ "$DISPLAY" ]; then
    emacsclient --eval "(progn (select-frame (make-frame-on-display \"$DISPLAY\"))
                               $runmagit)" 2>&1 |
    grep "Don't know how to create a frame on window system" > /dev/null
    #^Above is what you get when $DISPLAY is set but emacs was
    # built without X support.
    if [ $? = 0 ]; then
        emacsclient --tty --eval "$runmagit"
    fi
else
    emacsclient --create-frame --eval "$runmagit" 2>/dev/null
fi

if [ $? != 0 ]; then
    #Server not running or emacsclient not usable
    emacs --eval "$runmagit"
fi
