\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename ./magit.info
@settitle Ceci n'est pa un manuel
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@copying
Magit is an interface to the version control system Git, implemented
as an Emacs package.

This manual is only a stub, not even a draft.  The draft for what will
become the manual for the upcoming @code{2.1.0} release is currently
maintained in the webpage repository.  It will be moved into the
source repository once it is mostly finished.  You can read the draft
online at @uref{http://magit.vc/manual}.  The draft and earlier versions of
the manual can also be downloaded in various formats from that same
page.
@end copying

@dircategory Emacs
@direntry
* Magit: (magit).       Ceci n'est pa un manuel.
@end direntry

@finalout
@titlepage
@title Ceci n'est pa un manuel
@author Jonas Bernoulli
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Ceci n'est pa un manuel
@insertcopying
@end ifnottex




@bye
