name: Compile
on: [push, pull_request]
jobs:
  compile:
    name: Compile
    uses: | # zizmor: ignore[unpinned-uses] same maintainer as this repo
      emacscollective/workflows/.github/workflows/compile.yml@main
    permissions: {}
