name: Statistics
on:
  push:
    branches: main
  schedule:
    - cron: '3 13 * * 1'
jobs:
  stats:
    name: Statistics
    uses: | # zizmor: ignore[unpinned-uses] same maintainer as this repo
      emacscollective/workflows/.github/workflows/stats.yml@main
    permissions: {}
    secrets:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
